// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xgqhuxaeryowjxhdjvax.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhncWh1eGFlcnlvd2p4aGRqdmF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwMTczNjUsImV4cCI6MjA1NzU5MzM2NX0.brLiycV0CFSalOezEk73siULcyKf8KwUFjB_OCJo18s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);